### ISSUE TITLE
Violation of compareTo Invariants in TemplateFactory Causes Template Compilation Failures

### ISSUE THREAD

**Issue by samcgardner** [phax/ph-stx#2]
When trying to compile templates using ph-stx, it is possible to cause Java's TimSort implementation to throw IllegalArgumentException whilst trying to sort an Array of TemplateFactory instances. The root cause of this bug is that TemplateFactory's compareTo method falsely reports equality between signed zeroes of different types of NaN and !NaN. 

Since ph-stx's functionality is dependent on the current implementation of compareTo, I have submitted a PR to use a custom quicksort implementation to work around the issue. I will submit a reproduction case and regression test in due course, but as the code that causes the issue is private this will require some work. The proposed fix is available for you to glance over in the meantime.

**Comment by phax** [comment]
Hi. Thanks for the bug report. Can you potentially elaborate WHERE the problem occurs? Where am I sorting TemplateFactory objects ??? :)

Thanks

**Comment by samcgardner** [comment]
Lines 186 and 318 of AbstractGroupBase.java

(Sorry, OP should read "TemplateFactory.Instance" objects, my bad)

**Comment by samcgardner** [comment]
I've thrown up a regression test. Sadly, my fix doesn't work either as it hangs trying to sort the array :/

**Comment by samcgardner** [comment]
I've fixed it for realsies and added a regression test. I can't get your tests to run locally and I don't understand STX so the test is all over the shop, sorry about that.

**Comment by phax** [comment]
Please check if my fix - passing a custom `Comparator` - solves the issue. This looks a bit less invasive than your PR...

**Comment by samcgardner** [comment]
Changing the order into which TemplateFactory.Instances is breaking as it changes the order in which templates are applied. See the attached transformation and source XML for an example.
[xocs-enrichment.stx.txt](https://github.com/phax/ph-stx/files/1601112/xocs-enrichment.stx.txt)
[author.xml.txt](https://github.com/phax/ph-stx/files/1601115/author.xml.txt)

**Comment by phax** [comment]
Okay - basically I was trying to replace the code in the `compareTo` method with `Double.compare` without using a different sort algorithm, because I believe the `compareTo` should be corrected instead! hth

Edit: the previous commit seems to work...

**Comment by samcgardner** [comment]
I agree that fixing compareTo would be optimal, but I don't think any such change is possible without changing how templates will be applied.

I believe that previous commit will also potentially break existing templates as it modifies the compareTo. You could consider sorting with the legacy Array sort, which is more tolerant of compareTo invariants being violated.

**Comment by phax** [comment]
I must admit I'm not really an expert on that code. I was evaluating it for some Schematron validation but never found time to do it. Btw. XSLT3 will have streaming support :)
In the meantime, can't we find a way to reproduce the sorting? How come that it becomes `Double.NaN` anyway?

**Comment by samcgardner** [comment]
It becomes NaN in the case of template matches with an "or" pattern, e.g. match=a|b

I think we will struggle to recreate the existing behaviour if we change the comparator but may be able to avoid implementing our own sort to resolve the issue

**Comment by phax** [comment]
Anyway if you have a working solution, I'd be happy to include it :)

**Comment by samcgardner** [comment]
I'm afraid I don't have a better solution to offer than the original PR. I agree that reimplementing a basic sort is clunky but I don't see an alternative that doesn't force all library users to use the legacy Java merge sort.

**Comment by phax** [comment]
So I added the pimped QuickSort solution and using it in there. hth
